version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase
